services:
  apache-wp:
<<<<<<< HEAD
    image: apache-wp
    platform: linux/amd64
=======
    image: apache-wp:1.0.0
>>>>>>> 45a06ad4bd32ad0c2b8616faf3c237db5f8baf06
    container_name: apache-wp
    depends_on:
      - mysql
    ports:
      - 8081:80

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-apache
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wp1234
