services:
  nginx-wp:
    image: nginx-wp
    platform: linux/amd64
    container_name: nginx-wp
    depends_on:
      - mysql
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-nginx
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wp1234
